import React from 'react';
import { ArrowRight, BarChart3, Check, FileText, LockKeyhole, LogIn, Mail, Sparkles, UserPlus, Zap } from 'lucide-react';
import { TranslationJob } from '../../types';

interface AuthScreenProps { onSubmit: (email: string) => void; onSwitch: () => void; }

export const LoginScreen: React.FC<AuthScreenProps> = ({ onSubmit, onSwitch }) => (
  <AuthLayout eyebrow="Welcome back" title="Translate with confidence." description="Sign in to continue your document workspace and keep every translation job in one place." icon={<LogIn className="h-5 w-5" />}>
    <form className="space-y-4" onSubmit={(event) => { event.preventDefault(); onSubmit(String(new FormData(event.currentTarget).get('email'))); }}>
      <Field label="Work email" name="email" type="email" placeholder="you@company.com" required />
      <Field label="Password" name="password" type="password" placeholder="Enter your password" required />
      <button className="w-full rounded-xl bg-[#3538cd] px-4 py-3 text-sm font-bold text-white shadow-md transition hover:bg-[#2b2db5]">Sign in <ArrowRight className="ml-2 inline h-4 w-4" /></button>
    </form>
    <p className="mt-5 text-center text-xs text-slate-500">New to DocTranslate? <button onClick={onSwitch} className="font-bold text-[#3538cd] hover:underline">Create an account</button></p>
  </AuthLayout>
);

export const RegisterScreen: React.FC<AuthScreenProps> = ({ onSubmit, onSwitch }) => (
  <AuthLayout eyebrow="Start your workspace" title="Create your translation account." description="Begin with the free plan and keep your document history, usage and preferences together." icon={<UserPlus className="h-5 w-5" />}>
    <form className="space-y-4" onSubmit={(event) => { event.preventDefault(); onSubmit(String(new FormData(event.currentTarget).get('email'))); }}>
      <Field label="Name" name="name" type="text" placeholder="Your name" required />
      <Field label="Work email" name="email" type="email" placeholder="you@company.com" required />
      <Field label="Password" name="password" type="password" placeholder="Create a password" required />
      <button className="w-full rounded-xl bg-[#3538cd] px-4 py-3 text-sm font-bold text-white shadow-md transition hover:bg-[#2b2db5]">Create free account <ArrowRight className="ml-2 inline h-4 w-4" /></button>
    </form>
    <p className="mt-5 text-center text-xs text-slate-500">Already have an account? <button onClick={onSwitch} className="font-bold text-[#3538cd] hover:underline">Sign in</button></p>
  </AuthLayout>
);

const AuthLayout: React.FC<{ eyebrow: string; title: string; description: string; icon: React.ReactNode; children: React.ReactNode }> = ({ eyebrow, title, description, icon, children }) => (
  <section className="mx-auto grid min-h-[calc(100vh-9rem)] max-w-6xl items-center gap-12 px-4 py-12 lg:grid-cols-2">
    <div className="hidden rounded-3xl bg-[#171a52] p-10 text-white lg:block"><div className="mb-20 flex items-center gap-3 text-sm font-bold"><Sparkles className="h-5 w-5 text-cyan-300" /> DocTranslate AI</div><p className="text-sm font-bold uppercase tracking-[0.24em] text-cyan-300">Private document intelligence</p><h2 className="mt-5 text-4xl font-extrabold leading-tight">A calmer way to move complex documents across languages.</h2><div className="mt-10 space-y-4 text-sm text-indigo-100"><p><Check className="mr-2 inline h-4 w-4 text-cyan-300" />OCR-aware extraction and layout preservation.</p><p><Check className="mr-2 inline h-4 w-4 text-cyan-300" />Glossaries and quality warnings built into the workflow.</p><p><Check className="mr-2 inline h-4 w-4 text-cyan-300" />Progress you can understand at every stage.</p></div></div>
    <div className="mx-auto w-full max-w-md rounded-3xl border border-slate-200 bg-white p-7 shadow-xl sm:p-9"><div className="mb-7 flex h-11 w-11 items-center justify-center rounded-2xl bg-blue-50 text-[#3538cd]">{icon}</div><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#3538cd]">{eyebrow}</p><h1 className="mt-2 text-3xl font-extrabold tracking-tight text-slate-900">{title}</h1><p className="mt-3 text-sm leading-relaxed text-slate-500">{description}</p><div className="mt-7">{children}</div></div>
  </section>
);

const Field: React.FC<{ label: string; name: string; type: string; placeholder: string; required?: boolean }> = ({ label, name, type, placeholder, required }) => <label className="block text-xs font-bold text-slate-700">{label}<span className="relative mt-1.5 block"><input name={name} type={type} placeholder={placeholder} required={required} className="w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm font-medium text-slate-900 outline-none transition placeholder:text-slate-400 focus:border-[#3538cd] focus:bg-white focus:ring-4 focus:ring-indigo-100" />{type === 'email' ? <Mail className="pointer-events-none absolute right-3 top-3.5 h-4 w-4 text-slate-400" /> : <LockKeyhole className="pointer-events-none absolute right-3 top-3.5 h-4 w-4 text-slate-400" />}</span></label>;

export const DashboardScreen: React.FC<{ email: string; jobs: TranslationJob[]; onTranslate: () => void; onOpenJob: (job: TranslationJob) => void; onSignOut: () => void }> = ({ email, jobs, onTranslate, onOpenJob, onSignOut }) => <section className="mx-auto max-w-7xl space-y-7 px-4 py-8 sm:px-6 lg:px-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#3538cd]">Workspace</p><h1 className="mt-2 text-3xl font-extrabold tracking-tight text-slate-900">Good morning, {email.split('@')[0]}.</h1><p className="mt-2 text-sm text-slate-500">Your translation workspace at a glance.</p></div><div className="flex gap-2"><button onClick={onSignOut} className="rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-bold text-slate-600 hover:bg-slate-50">Sign out</button><button onClick={onTranslate} className="rounded-xl bg-[#3538cd] px-5 py-3 text-sm font-bold text-white shadow-md hover:bg-[#2b2db5]">New translation <ArrowRight className="ml-2 inline h-4 w-4" /></button></div></div><div className="grid gap-4 sm:grid-cols-3"><Metric icon={<FileText />} label="Total jobs" value={String(jobs.length)} /><Metric icon={<Check />} label="Completed" value={String(jobs.filter((job) => job.status === 'completed').length)} /><Metric icon={<BarChart3 />} label="Free plan usage" value="2 / 10 jobs" /></div><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><h2 className="font-bold text-slate-900">Recent translations</h2><span className="text-xs font-semibold text-slate-400">Updated just now</span></div><div className="mt-5 divide-y divide-slate-100">{jobs.slice(0, 4).map((job) => <button key={job.id} onClick={() => onOpenJob(job)} className="flex w-full items-center justify-between gap-4 py-4 text-left hover:bg-slate-50"><span className="min-w-0"><span className="block truncate text-sm font-bold text-slate-800">{job.filename}</span><span className="mt-1 block text-xs text-slate-400">{job.sourceLang} to {job.targetLang} · {job.createdAt}</span></span><span className="shrink-0 rounded-full bg-slate-100 px-3 py-1 text-xs font-bold text-slate-600">{job.progress}%</span></button>)}</div></div></section>;

export const UsageScreen: React.FC = () => <SimplePage eyebrow="Usage" title="Understand your consumption." description="Keep commercial quotas separate from technical model usage."><div className="grid gap-4 sm:grid-cols-3"><Metric icon={<FileText />} label="Jobs this month" value="2 / 10" /><Metric icon={<Zap />} label="Pages processed" value="84 / 500" /><Metric icon={<BarChart3 />} label="Model tokens" value="14,280" /></div><div className="mt-6 rounded-2xl border border-slate-200 bg-white p-6"><h2 className="font-bold text-slate-900">Free plan limits</h2><div className="mt-5 space-y-5"><UsageBar label="Jobs per day" value="2 of 10" progress={20} /><UsageBar label="Maximum file size" value="25 MiB" progress={55} /><UsageBar label="Monthly tokens" value="14,280 of 100,000" progress={14} /></div></div></SimplePage>;

export const PlanScreen: React.FC = () => <SimplePage eyebrow="Plans" title="Choose the right pace for your work." description="The free plan is available now. Premium billing is coming in a future release."><div className="grid gap-5 lg:grid-cols-2"><PlanCard name="Free" price="$0" features={['25 MiB maximum file size', '10 jobs per day', 'OCR enabled', 'Standard processing']} /><PlanCard name="Premium" price="Coming soon" featured features={['Larger files and page limits', 'Priority processing', 'Expanded monthly tokens', 'Reusable glossaries and styles']} /></div></SimplePage>;

const SimplePage: React.FC<{ eyebrow: string; title: string; description: string; children: React.ReactNode }> = ({ eyebrow, title, description, children }) => <section className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8"><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#3538cd]">{eyebrow}</p><h1 className="mt-2 text-3xl font-extrabold tracking-tight text-slate-900">{title}</h1><p className="mt-2 text-sm text-slate-500">{description}</p><div className="mt-7">{children}</div></section>;
const Metric: React.FC<{ icon: React.ReactNode; label: string; value: string }> = ({ icon, label, value }) => <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-blue-50 text-[#3538cd]">{icon}</span><p className="mt-4 text-xs font-semibold text-slate-500">{label}</p><p className="mt-1 text-2xl font-extrabold text-slate-900">{value}</p></div>;
const UsageBar: React.FC<{ label: string; value: string; progress: number }> = ({ label, value, progress }) => <div><div className="flex justify-between text-xs font-bold text-slate-700"><span>{label}</span><span className="text-slate-400">{value}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-[#3538cd]" style={{ width: `${progress}%` }} /></div></div>;
const PlanCard: React.FC<{ name: string; price: string; features: string[]; featured?: boolean }> = ({ name, price, features, featured }) => <div className={`rounded-2xl border p-6 ${featured ? 'border-[#3538cd] bg-[#171a52] text-white shadow-xl' : 'border-slate-200 bg-white'}`}><div className="flex items-center justify-between"><h2 className="text-xl font-extrabold">{name}</h2>{featured && <span className="rounded-full bg-cyan-300 px-3 py-1 text-[10px] font-black uppercase tracking-wider text-[#171a52]">Future</span>}</div><p className={`mt-5 text-4xl font-extrabold ${featured ? 'text-white' : 'text-slate-900'}`}>{price}{price.startsWith('$') && <span className="text-sm font-semibold opacity-60"> / month</span>}</p><ul className={`mt-6 space-y-3 text-sm ${featured ? 'text-indigo-100' : 'text-slate-600'}`}>{features.map((feature) => <li key={feature}><Check className="mr-2 inline h-4 w-4 text-cyan-400" />{feature}</li>)}</ul></div>;
